### ISSUE TITLE
Sharing efforts

### ISSUE THREAD

**Issue by jcelerier** [forart/HyMPS#3]
Hello :) 

seeing the list of things mentioned in this repo makes me thing that we have similar goals.

I've been working for the last few months on [Avendish](https://github.com/celtera/avendish), a C++ library which is able to  define media objects that can trivially be compiled against various media systems & APIs such as Max, Pd, etc. , as zero-runtime-cost abstraction (and very low compile-time cost ; the full test suite which builds ~500 different objects being built compiles in 3 to 7 minutes on GH actions depending on the compiler used).

In particular, it is able to express audio/midi processors but also message-based objects and more recently GPU based objects and is to be used as the plug-in API to https://ossia.io ; the sequencer I am working on.

The issues in the repo: https://github.com/celtera/avendish/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc list all the interesting media systems I could find - my short term goal is to port at least one effect of each of those to show that this is possible and makes things both easier and more cross-platform/system. 

So if at any point you wish to collaborate this could lead to interesting things I believe!

**Comment by forart** [comment]
Hi there, 1st of all thanks for your constructive contribution !

At the moment we don't have any "embedded" developer (we have collaborated with [NASPRO](http://naspro.sourceforge.net/) author, in the past) so, as NPO, we decided to _stimulate_ possible collaborations between (minor ones, in particular) projects/devs.

[Avendish](https://github.com/celtera/avendish) sounds very interesting so we'll try to promote its adoption in our channels.

Last but not least, we will "grab" your listed finds: do you have any preference about the category in which to insert them ?

Thanks again and hope we can help you/your projects.

**Comment by jcelerier** [comment]
Hi ! thanks, I'm on a contract this week, looking at this quickly. I agree about the GH discussion, it looks like a good place to talk ! 

cheers

**Comment by forart** [comment]
OK, we opened a dedicated discussion about the (logical) collection re-organization:

https://github.com/forart/HyMPS/discussions/11

Suggestions and (hopefully constructive) criticism from all are always welcomed.
