### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by andrepxx** [forart/HyMPS#6]
The line for the *go-dsp-guitar* project is incorrect. It refers to the wrong projects for the information about programming language and last commit.

The code in *GuitarDSPs.md* says:

`|[go-dsp-guitar](https://github.com/andrepxx/go-dsp-guitar#go-dsp-guitar)|A cross-platform multichannel multi-effects processor for electric guitars and other instruments|![](https://img.shields.io/github/languages/top/andrepxx/go-dsp-guitar?color=pink&style=flat-square)|![](https://flat.badgen.net/github/license/kaktus3000/HighGain?label=)|![](https://flat.badgen.net/github/last-commit/kaktus3000/HighGain?label=)|`

However, it should rather say the following:

`|[go-dsp-guitar](https://github.com/andrepxx/go-dsp-guitar#go-dsp-guitar)|A cross-platform multichannel multi-effects processor for electric guitars and other instruments|![](https://img.shields.io/github/languages/top/andrepxx/go-dsp-guitar?color=pink&style=flat-square)|![](https://flat.badgen.net/github/license/andrepxx/go-dsp-guitar?label=)|![](https://flat.badgen.net/github/last-commit/andrepxx/go-dsp-guitar?label=)|`

Regards.

**Comment by forart** [comment]
Just cut'n'pasted your correction.

(curiosity: can 3rd-party users post changes to our "code" directly in gh?)

**Comment by forart** [comment]
note: Discussions are active, if you have any suggestion (about categorizations too)...

Let's keep in touch !

**Comment by andrepxx** [comment]
Well yes, I could fork the repo and submit a pull request. But I didn't wanna fork it and I saw that, so far, all commits in this repo were from you and I didn't wanna "break" that "row" by submitting my own commit. ;-)

**Comment by forart** [comment]
> Well yes, I could fork the repo and submit a pull request. But I didn't wanna fork it and I saw that, so far, all commits in this repo were from you and I didn't wanna "break" that "row" by submitting my own commit. ;-)

Yep, GH is a bit "strange"... we happened to unintentionally fork some repos ([RealBasicVSR, YAMS ?](https://github.com/forart?tab=repositories) Of course we have doxed them, but never - intentionally - forked).

We do also noticed some "caching effect" by badges generation services, anyway - except for some (inevitable, sigh!) human error and some limit (it would be great to let visitors to dinamically apply orderings) - we are quite happy of "our" markdown-tables format.

Anyway we would like to focus on categorizations (softwares are not lacking) 'cause there's some mess... 
...example: under H_AUDIO could be more useful to have more macro-categories (eg. INSTRUMENTS -> [Voice](https://github.com/forart/HyMPS/blob/main/Voice.md)[](https://github.com/forart/HyMPS#guitar), [Guitar](https://github.com/forart/HyMPS/blob/main/GuitarDSPs.md)[](https://github.com/forart/HyMPS#bass), [Bass](https://github.com/forart/HyMPS/blob/main/BassDSPs.md), Drums...) even for GH-page readability, anyway the project goal is to build a platform-indipendent open source "libraries-distro"  for (artistic) multimedia content creation.

We do need a dev-oriented categorization, but we - actually - don't have any "embedded" dev in our organization (as we also told to @jcelerier [here](https://github.com/forart/HyMPS/issues/3#issuecomment-1094600441))...

...so suggestions are welcomed.

;)
